keys:
  - &users:
    - &skarmux age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
  - &hosts:
    - &teridax age1kmgp8gj6pg6g7k9xhx35yc4zcktqmjwp2pfn5vpmjd09ky3e8avsah4wgg
    - &ignika age1pyj03ga9w6mqar9s99w4q27dwvgmjcm94a72a00x2n2uucw23q4sz3ww0z
    - &pewku age1uh2hsdffutrymarqtsdhk3qcn5fvj3455mzjpqfcxvn7h4ey2axq9xjh7j
creation_rules:
  - path_regex: home/skarmux/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
  - path_regex: home/skarmux/llm/keys.json
    key_groups:
    - age:
      - *skarmux
  - path_regex: nixos/teridax/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *teridax
  - path_regex: nixos/ignika/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *ignika
  - path_regex: nixos/pewku/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *pewku
  - path_regex: secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *teridax
      - *ignika
      - *pewku
