keys:
  - &users:
    - &skarmux age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
  - &hosts:
    - &teridax age1kmgp8gj6pg6g7k9xhx35yc4zcktqmjwp2pfn5vpmjd09ky3e8avsah4wgg
    - &ignika age1pyj03ga9w6mqar9s99w4q27dwvgmjcm94a72a00x2n2uucw23q4sz3ww0z
    - &pewku age1ep58ggw4xvqwcecac6vngmy7pw7chpsjm5ftlg53ax5kwkjr63nss5hdv4
creation_rules:
  - path_regex: home/skarmux/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
  - path_regex: config/nixos/teridax/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *teridax
  - path_regex: config/nixos/ignika/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *ignika
  - path_regex: config/nixos/pewku/secrets.ya?ml$
    key_groups:
    - age:
      - *skarmux
      - *pewku
