users:
    skarmux: ENC[AES256_GCM,data:f4GkqTrgRy3i68mPxnZapqn3kevfrLE+B3do6NF2X/d0I6HI9fXUY+EBKjbkTAcJkW6UVm6EY8TCkJxCk8/jKOI8FKjX2uiOxA==,iv:B5KZyvLyV8IZDBsJBV5oIESso1ToagbxeUdnuBi8S8k=,tag:rZL31lQ5JaR+tYCxJm+V0w==,type:str]
wireguard:
    private: ENC[AES256_GCM,data:duFcnSbVaqKys0chuSt/1hhYnH1Tk5Z8WkbFlCEGSM08Kb6S54Bw5nWwy4s=,iv:PxUebC/fIPIpokkKS8cNOz3l6XROjW3FL5bdeI8TP2k=,tag:EgadrzhwFYo5AaZ8GbOjXg==,type:str]
    preshared: ENC[AES256_GCM,data:6C1xqk41iGSbj1LD+ejV8QB3viA5XoZ0+Mvc6lGgQATSiK9NPuLpk0UBdPU=,iv:ZKKkIG0eHB+upzM3w+IzFW9wtz4abdhRKUUvzkO8LBE=,tag:jUbi4uYgQPxkN6FfntNTnQ==,type:str]
sops:
    age:
        - recipient: age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZkRydWJKWUFzNldQdFFX
            RlhFajh1SG1jRWYzQ3NvQWFVcHZEdmdwMjFrCnM0ZTJ0WnY4VzdTcjRueXN1WmFr
            c25kbmZSNHJqMjZuWEM4SjF2eGR5QVUKLS0tIFZLSUJoRjZ6ZEVMN3ZaNE8rUFlC
            QmJYd3krWTduVmlmaUVMbFdVSDNobEkKZIO8gLOdb746fIIvCCxMpRXPBz8SWKz6
            MLRkWWeKcVt530sBCQYj5Ws2wlCwyYOBN4jxU8nugHc/pr6GpFAK1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ucm0frs5cchkrv2mzfuaqv6h0d4eu94y6ugddag2xzphxvp4ud7sej3mz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS3F5ZVdDK2dSdVNaUFk4
            U0kzV0x4VUFzc3lBcEsxRDBQbXJHQXZFU2lBCmE1Z2ZuZmNnT1Q3cUtGZmttVzlM
            bzZBOWppa1VNWHR2QmxneGVkQlR2T1UKLS0tIDd2b1JWdkFTTzFnbDM3YlUvaWFN
            bWlEeFBGRzBsN1VqdE95OXVBOG1HbkkKdr5eVXrwRO6LQgDfvPHfh/zAtzNyCUQW
            iq6800IT9khZpsC41sKgr9iYDokJSAgBwG1DWlnVi6IRIkIxPPJGVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T22:00:00Z"
    mac: ENC[AES256_GCM,data:5R+iLYyTzvEk9lIeshS5j/ZxhQXt4pjXzVQLZMU5m78SRVvt87qef4KWCcwSypmCiB8zuMpw1PHYU4utMycrZJ7PrYEIxbWDyw8mS4IfafbqwhzcH0TLYyJtru1AnTidcAhFtiMScjHhDxDQKBKgY2VvyU5Kv2NHhdK9vg2L+rw=,iv:KKU9sPpGMc8i0lWAUDKkmD0JdDv81gQ8H06ODp4KqS0=,tag:FYlV1TswliPbFbMOzf4MBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
