users:
    skarmux: ENC[AES256_GCM,data:QZAQjBe2hPE=,iv:1HK5y6VzptkQ1EJtFFNzBk2tgRtIdDCfBaWnfjknqZk=,tag:42loAjijyEXvU7dKr6/vJA==,type:str]
sops:
    age:
        - recipient: age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZkRydWJKWUFzNldQdFFX
            RlhFajh1SG1jRWYzQ3NvQWFVcHZEdmdwMjFrCnM0ZTJ0WnY4VzdTcjRueXN1WmFr
            c25kbmZSNHJqMjZuWEM4SjF2eGR5QVUKLS0tIFZLSUJoRjZ6ZEVMN3ZaNE8rUFlC
            QmJYd3krWTduVmlmaUVMbFdVSDNobEkKZIO8gLOdb746fIIvCCxMpRXPBz8SWKz6
            MLRkWWeKcVt530sBCQYj5Ws2wlCwyYOBN4jxU8nugHc/pr6GpFAK1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ucm0frs5cchkrv2mzfuaqv6h0d4eu94y6ugddag2xzphxvp4ud7sej3mz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS3F5ZVdDK2dSdVNaUFk4
            U0kzV0x4VUFzc3lBcEsxRDBQbXJHQXZFU2lBCmE1Z2ZuZmNnT1Q3cUtGZmttVzlM
            bzZBOWppa1VNWHR2QmxneGVkQlR2T1UKLS0tIDd2b1JWdkFTTzFnbDM3YlUvaWFN
            bWlEeFBGRzBsN1VqdE95OXVBOG1HbkkKdr5eVXrwRO6LQgDfvPHfh/zAtzNyCUQW
            iq6800IT9khZpsC41sKgr9iYDokJSAgBwG1DWlnVi6IRIkIxPPJGVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T22:47:17Z"
    mac: ENC[AES256_GCM,data:roQZiyLBs8NReJEOJxZkQeZsIXzFCPH/kG0hgrShZN3DDzlWeWLHMMyDCqLpJq3Xp7GC1/Ah3pp/MCC6ybCCl5B9Hldplsn+d11t7FOj0o4cS0KLguheGa0DmNZnAZbHww0cRnlXwTMOM/SkJ0WnFeDeySt6S2VqDN18fF3fyMM=,iv:PFw4yyCF6TkbBcZmdy6uMVLRqfqH0+ays+dO2ZlumIQ=,tag:7EURThaMLkCDn7bGu2RZzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
