users:
    skarmux: ENC[AES256_GCM,data:QZAQjBe2hPE=,iv:1HK5y6VzptkQ1EJtFFNzBk2tgRtIdDCfBaWnfjknqZk=,tag:42loAjijyEXvU7dKr6/vJA==,type:str]
sops:
    age:
        - recipient: age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbTV0TnVMVnVITzRuN2Mv
            V01oSGZUcHNiVXFENG1JN3FQWFJlTTNGTFZNCkQveXQ2SW5CZjlyWGNQVmlwdXky
            TVcwL01haWlMbkdDZUJkM3M1ZE5zUE0KLS0tIDQvUUgrZWhCQkJjcnFKb2NyNGlG
            SEFjZy9pNTV3SEJMM3JtaHZwdUJhd2sKMdVDRWejMrsoaXOjVQsDMAl1rljujXg2
            DfCWUGarzRBJ9Eiyuzfb9V97t+oKfSqTc4WR2vbhC/tMEQB0BBv/Tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kmgp8gj6pg6g7k9xhx35yc4zcktqmjwp2pfn5vpmjd09ky3e8avsah4wgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmtLdjExdzRxeVNHb3Rt
            TVdYaGZHQkNoeXpPVmQ1NXNFdHcxS3FDOGtVCkU0MENHQ2xkaWVDVE5mZXN2OE9B
            Z2hPbVFPQksxZTNOL1ZhYTE0emlYZFUKLS0tIE94eDR0c1lOYVNPdldmQlVua2ow
            aDRBakdLRk16cVB0TE9xNFR2NmFiUGcKkyfbtc2pT/X74yTUT99uGt2QlbIfw3qD
            s+A3CRT2D8tI887tGh4NVOHIIip2+YMycE7VbCdbI/j97R++jt9oqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T22:47:17Z"
    mac: ENC[AES256_GCM,data:roQZiyLBs8NReJEOJxZkQeZsIXzFCPH/kG0hgrShZN3DDzlWeWLHMMyDCqLpJq3Xp7GC1/Ah3pp/MCC6ybCCl5B9Hldplsn+d11t7FOj0o4cS0KLguheGa0DmNZnAZbHww0cRnlXwTMOM/SkJ0WnFeDeySt6S2VqDN18fF3fyMM=,iv:PFw4yyCF6TkbBcZmdy6uMVLRqfqH0+ays+dO2ZlumIQ=,tag:7EURThaMLkCDn7bGu2RZzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
