users:
    skarmux: ENC[AES256_GCM,data:f4GkqTrgRy3i68mPxnZapqn3kevfrLE+B3do6NF2X/d0I6HI9fXUY+EBKjbkTAcJkW6UVm6EY8TCkJxCk8/jKOI8FKjX2uiOxA==,iv:B5KZyvLyV8IZDBsJBV5oIESso1ToagbxeUdnuBi8S8k=,tag:rZL31lQ5JaR+tYCxJm+V0w==,type:str]
sops:
    age:
        - recipient: age1p6rz0367carqljqz3493y2z2wgmsw2xh0yduxz8sd0jn45n0k49ske3k4t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZkRydWJKWUFzNldQdFFX
            RlhFajh1SG1jRWYzQ3NvQWFVcHZEdmdwMjFrCnM0ZTJ0WnY4VzdTcjRueXN1WmFr
            c25kbmZSNHJqMjZuWEM4SjF2eGR5QVUKLS0tIFZLSUJoRjZ6ZEVMN3ZaNE8rUFlC
            QmJYd3krWTduVmlmaUVMbFdVSDNobEkKZIO8gLOdb746fIIvCCxMpRXPBz8SWKz6
            MLRkWWeKcVt530sBCQYj5Ws2wlCwyYOBN4jxU8nugHc/pr6GpFAK1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ucm0frs5cchkrv2mzfuaqv6h0d4eu94y6ugddag2xzphxvp4ud7sej3mz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS3F5ZVdDK2dSdVNaUFk4
            U0kzV0x4VUFzc3lBcEsxRDBQbXJHQXZFU2lBCmE1Z2ZuZmNnT1Q3cUtGZmttVzlM
            bzZBOWppa1VNWHR2QmxneGVkQlR2T1UKLS0tIDd2b1JWdkFTTzFnbDM3YlUvaWFN
            bWlEeFBGRzBsN1VqdE95OXVBOG1HbkkKdr5eVXrwRO6LQgDfvPHfh/zAtzNyCUQW
            iq6800IT9khZpsC41sKgr9iYDokJSAgBwG1DWlnVi6IRIkIxPPJGVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T15:04:49Z"
    mac: ENC[AES256_GCM,data:BG97X35cMI81S33nJNe2WnsjMm6QyPJYNZ6sOB5+bkhSmzxJKTP5EOKv5qZGiLsyzOMr19/Y7pa4Rw+sMwO5kytzzLfp9JaN18G0M/Npi6bhGYUplP9QIW9wtvB/03jf2wh7rMyp/E30oiH/Ac5Y1z1pr/vQnqxzkGjDADCocws=,iv:ZOYk8x9MuhpRYvwdDNvgM8dAKzyf7qUXfnh4AS/5DT8=,tag:8qAMOOm3wt1kaBuJupuZtg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
