{ lib, inputs, ... }:
{
  imports = [ inputs.disko.nixosModules.disko ];

  # Sops needs access to persisted private keys to
  # generate /run/secrets before booting is completed
  fileSystems."/persist".neededForBoot = true;

  disko.devices.disk.main = {
    type = "disk";
    device = "/dev/nvme0n1"; # names can vary!!!
    content = {
      type = "gpt";
      partitions = {
        ESP = {
          type = "EF00";
          size = "512M";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
            mountOptions = [ "umask=0077" ];
          };
        };
        luks = {
          size = "100%";
          content = {
            type = "luks";
            name = "crypted";
            # disable settings.keyFile if you want to use interactive password entry
            # passwordFile = "/tmp/secret.key"; # Interactive TODO needs to be generated by script
            settings = { allowDiscards = true; };
            content = {
              type = "btrfs";
              extraArgs = [ "-f" ]; # Override existing partition
              # `noatime` (No Access Time) disables the writing of the last access time on files/directories.
              # It reduces writes and therefore increases performance and disk longevity.
              subvolumes = {
                "/root" = {
                  mountpoint = "/";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "/nix" = {
                  mountpoint = "/nix";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                # I don't want weird symlinking happening in my home directory
                "/home" = {
                  mountpoint = "/home";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "/persist" = {
                  mountpoint = "/persist";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
              };
            };
          };
        };
      };
    };
  };
}
